2021-11-06 15:33:12,883 - INFO - Сервер начал с параметрами: 127.0.0.1:7777
2021-11-06 15:34:31,490 - INFO - Сервер начал с параметрами: 127.0.0.1:7777
2021-11-06 15:41:54,831 - INFO - Сервер начал с параметрами: 127.0.0.1:7777
2021-11-06 15:43:33,690 - INFO - Сервер начал с параметрами: 127.0.0.1:7777
2021-11-06 15:51:42,157 - INFO - Сервер начал с параметрами: 127.0.0.1:7777
2021-11-06 15:52:27,272 - INFO - Сервер начал с параметрами: 127.0.0.1:7777
2021-11-06 15:58:19,815 - INFO - Сервер начал с параметрами: 127.0.0.1:7777
2021-11-06 16:01:57,688 - INFO - Сервер начал с параметрами: 127.0.0.1:7777
2021-11-06 16:09:24,653 - INFO - Сервер начал с параметрами: 127.0.0.1:7777
2021-11-06 16:28:20,073 - INFO - Сервер начал с параметрами: 127.0.0.1:7777
2021-11-06 16:28:24,426 - INFO - Client detected ('127.0.0.1', 58028)
2021-11-06 16:31:39,035 - INFO - Сервер начал с параметрами: 127.0.0.1:7777
2021-11-06 16:31:47,116 - INFO - Client detected ('127.0.0.1', 58064)
2021-11-06 16:31:53,027 - DEBUG - validate_request - with args:({'action': '123', 'time': '2021-11-06T16:31:53.026481', 'user': {'account_name': 'anonim', 'status': 'I am here!'}, 'data': 'test'},), {}
2021-11-06 16:31:53,046 - ERROR - Action 123 does not exits
2021-11-06 16:31:53,046 - DEBUG - make_404 - with args:({'action': '123', 'time': '2021-11-06T16:31:53.026481', 'user': {'account_name': 'anonim', 'status': 'I am here!'}, 'data': 'test'},), {}
2021-11-06 16:31:53,047 - DEBUG - make_response - with args:({'action': '123', 'time': '2021-11-06T16:31:53.026481', 'user': {'account_name': 'anonim', 'status': 'I am here!'}, 'data': 'test'}, 404, 'Action is not supported'), {}
2021-11-06 16:44:42,797 - DEBUG - validate_request - with args:({'action': 'test', 'time': '2021-11-06T16:44:42.791895', 'user': {'account_name': 'anonim', 'status': 'I am here!'}, 'data': 'test'},), {}
2021-11-06 16:44:42,799 - ERROR - Action test does not exits
2021-11-06 16:44:42,799 - DEBUG - make_404 - with args:({'action': 'test', 'time': '2021-11-06T16:44:42.791895', 'user': {'account_name': 'anonim', 'status': 'I am here!'}, 'data': 'test'},), {}
2021-11-06 16:44:42,799 - DEBUG - make_response - with args:({'action': 'test', 'time': '2021-11-06T16:44:42.791895', 'user': {'account_name': 'anonim', 'status': 'I am here!'}, 'data': 'test'}, 404, 'Action is not supported'), {}
2021-11-06 16:45:38,873 - DEBUG - validate_request - with args:({'action': 'exit', 'time': '2021-11-06T16:45:38.872407', 'user': {'account_name': 'anonim', 'status': 'I am here!'}, 'data': 'exit'},), {}
2021-11-06 16:45:38,873 - DEBUG - get_exit - with args:({'action': 'exit', 'time': '2021-11-06T16:45:38.872407', 'user': {'account_name': 'anonim', 'status': 'I am here!'}, 'data': 'exit'},), {}
2021-11-06 16:45:38,874 - DEBUG - make_response - with args:({'action': 'exit', 'time': '2021-11-06T16:45:38.872407', 'user': {'account_name': 'anonim', 'status': 'I am here!'}, 'data': 'exit'}, 200, 'exit'), {}
2021-11-06 16:45:38,874 - INFO - Request is valid and processed by controller
2021-11-06 16:46:10,679 - DEBUG - validate_request - with args:({'action': 'test', 'time': '2021-11-06T16:46:10.678672', 'user': {'account_name': 'anonim', 'status': 'I am here!'}, 'data': 'test'},), {}
2021-11-06 16:46:10,679 - ERROR - Action test does not exits
2021-11-06 16:46:10,679 - DEBUG - make_404 - with args:({'action': 'test', 'time': '2021-11-06T16:46:10.678672', 'user': {'account_name': 'anonim', 'status': 'I am here!'}, 'data': 'test'},), {}
2021-11-06 16:46:10,679 - DEBUG - make_response - with args:({'action': 'test', 'time': '2021-11-06T16:46:10.678672', 'user': {'account_name': 'anonim', 'status': 'I am here!'}, 'data': 'test'}, 404, 'Action is not supported'), {}
2021-11-06 19:41:51,299 - INFO - Сервер начал с параметрами: 127.0.0.1:7777
2021-11-06 19:44:03,491 - INFO - Сервер начал с параметрами: 127.0.0.1:7777
2021-11-06 19:44:07,542 - INFO - Client detected ('127.0.0.1', 59488)
2021-11-06 19:44:13,655 - DEBUG - validate_request - with args:({'action': '123', 'time': '2021-11-06T19:44:13.653967', 'user': {'account_name': 'anonim', 'status': 'I am here!'}, 'data': '11'},), {}
2021-11-06 19:44:13,665 - ERROR - Action 123 does not exits
2021-11-06 19:44:13,666 - DEBUG - make_404 - with args:({'action': '123', 'time': '2021-11-06T19:44:13.653967', 'user': {'account_name': 'anonim', 'status': 'I am here!'}, 'data': '11'},), {}
2021-11-06 19:44:13,666 - DEBUG - make_response - with args:({'action': '123', 'time': '2021-11-06T19:44:13.653967', 'user': {'account_name': 'anonim', 'status': 'I am here!'}, 'data': '11'}, 404, 'Action is not supported'), {}
